# Generated by Django 3.1 on 2020-08-13 08:04

from django.db import migrations
from datetime import date
from games.models import PlatformChoices
import itertools


def add_initial_data(apps, _):
    AgeRating = apps.get_model("games", "AgeRating")
    Game = apps.get_model("games", "Game")

    age_ratings = [AgeRating(rating=rating) for rating in range(1, 13)]
    AgeRating.objects.bulk_create(age_ratings)
    age_ratings = AgeRating.objects.all()

    today = date.today()

    # children's games
    children_games = [
        Game(
            name="Game 1",
            rating=age_ratings[0],
            release_date=today,
            platform=PlatformChoices.PS4,
        ),
        Game(
            name="Game 2",
            rating=age_ratings[1],
            release_date=date(today.year, 2, 1),
            platform=PlatformChoices.XBOX,
        ),
    ]

    # 18+ games
    mature_games = [
        Game(
            name="Game 3",
            rating=age_ratings[11],
            release_date=date(today.year - 1, 8, 12),
            platform=PlatformChoices.PS4,
        ),
        Game(
            name="Game 4",
            rating=age_ratings[10],
            release_date=date(today.year, 5, 12),
            platform=PlatformChoices.XBOX,
        ),
    ]

    Game.objects.bulk_create(itertools.chain(children_games, mature_games))


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data, migrations.RunPython.noop, atomic=True)
    ]
